apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  namespace: mad-eks-ns1
  labels:
    app: java-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp
        image: 730335332563.dkr.ecr.ap-south-1.amazonaws.com/madecr01:1dafd6f
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: java-webapp-service
  namespace: mad-eks-ns1
spec:
  type: LoadBalancer
  selector:
    app: java-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

