name: 'Terraform'

on:
  push:
    branches: []
  
jobs:
    terraform:
      name: 'Terraform'
      env:
        # AWS secrets
        AWS_ACCESS_KEY_ID: ${{ secrets.AAWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

      runs-on: ubuntu-latest
      environment: production

      steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.2.5

        - name: Terraform Init   
          run: |
            cd terraform
            terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="access_key=${AWS_ACCESS_KEY_ID}" -backend-config="secret_key=${AWS_SECRET_ACCESS_KEY}"


        - name: Terraform Plan
          run: |
            working-directory: ./terraform
            tterraform plan -input=false

        - name: Terraform Init
          if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
          run: |
            working-directory: ./terraform
            terraform apply -auto-approve -input=false
          
         

        
